### ISSUE TITLE
Why do you block no-cache responses

### ISSUE THREAD

**Issue by Zvezdin** [facebookincubator/meta-code-verify#166]
What is the security benefit of blocking no-cache responses? I presume to prevent a verified cross-origin script from reloading to a different, unverified version. How can this happen during one browsing session, and wouldn't other cache control request/response directives still allow for a malicious reload of a script nonetheless?

**Comment by rich-hansen** [comment]
That's not what that code is doing. It's not blocking the request. It's introspecting it. If the server is sending nocache header, it's possibly for the purpose of sending a different responses at different times.

For example, send a malicious payload to the client for the page with nocache header, then when the extension attempts to verify, send a non-malicious version. This is an attempt to prevent circumvention of verification.
