### ISSUE TITLE
the extension causing problem doesnt match the known_extension_hash

### ISSUE THREAD

**Issue by spiritbroski** [facebookincubator/meta-code-verify#211]
@rich-hansen sorry for bothering you once again but it is kinda weird behaviour i notice when i build meta-code-verify locally i got two extension installed 

![image](https://user-images.githubusercontent.com/62529025/232671995-a468f830-e059-4dc5-9424-808158e7ad30.png)

which is authentication and phantom, i try to debug what extension is causing risk when i go to whatsapp web 

![image](https://user-images.githubusercontent.com/62529025/232672208-091bb1ec-48eb-4739-8c08-d37cc9fdd6e4.png)

And this is what i got:

![image](https://user-images.githubusercontent.com/62529025/232672266-afde20bc-86bb-4e30-92cb-acd148909c76.png)

https://github.com/facebookincubator/meta-code-verify/blob/main/src/js/config.ts#L59

which is the adlock extension im using brave browser and no adlock installed, how come it detected as adlock when debugging the code actually refers to inline binary transparency manifest hash 

![image](https://user-images.githubusercontent.com/62529025/232675647-8f030561-0a04-4ed1-8ac6-2d7934b9522a.png)

![image](https://user-images.githubusercontent.com/62529025/232675716-d464f9b1-6eb9-4909-ab23-5998fae4ac1d.png)

could you please shed light on this because i just confused to how this works if my other extension is causing problem the hash should be coming from them not an inline hash js script right?

**Comment by spiritbroski** [comment]
its kinda weird when there is an extension the data-binary-transparency-hash-key="inline-js-4b79b6dc91a7ee33373b115991c3eb287ed710cfb6708421b4cab682eddbfcbd" doesnt show its innerHTML, but when there is no extension it show its innerHTML see this picture the left is with the extension the right it isnt, it makes sense that there is an extension there but it doesnt make sense because the extension doesnt inject any script at all, but point to the inline hash as the cause of the error

![image](https://user-images.githubusercontent.com/62529025/232730302-4b9a9869-7d43-4068-bfc6-dbc7cbf541c4.png)

**Comment by spiritbroski** [comment]
in facebook also its fine even with two extension installed 
![image](https://user-images.githubusercontent.com/62529025/232733491-696655ca-49b9-4a83-9fab-46ce920d0a2d.png)

**Comment by rich-hansen** [comment]
> i try to debug what extension is causing risk when i go to whatsapp web

The easiest way is to disable each extension individually from the extensions view and reload the page. That'll tell you which one is problematic.

> im using brave browser

Do you see it in Chrome? As they're both chromium based, should have the same base behavior. Maybe something with Brave's built in adblock is causing issues?

> but it doesnt make sense

It does look strange on the surface.

**Comment by spiritbroski** [comment]
@rich-hansen thanks for answering actually it also happen in edge, blank <script></script> like this will make the code verify think that adlock is causing issues
