### ISSUE TITLE
Validation failure - download button doesn't work

### ISSUE THREAD

**Issue by scriptjunkie** [facebookincubator/meta-code-verify#237]
I received a validation failure on WhatsApp Web a day or two ago. Concerned at the possibility of some kind of attack I tried to download the zip but the download button did nothing. I would just click it and nothing would happen, even when waiting for quite a while. It is not reproducing right now (green check now) so all I have are screenshots. Please advise as to next steps.
![image](https://github.com/facebookincubator/meta-code-verify/assets/1174495/c2c1a562-b918-4fd4-8c24-37b3f695f2c1)
![image](https://github.com/facebookincubator/meta-code-verify/assets/1174495/593d7f0e-bab2-4382-9d3a-c85fea3a0a25)

**Comment by scriptjunkie** [comment]
I got it reproduced. It's currently erroring at `TypeError: window.showSaveFilePicker is not a function` at
```
    async function downloadJSToZip() {
      const fileHandle = await window.showSaveFilePicker({
```
in contentWA.js which as part of the [File System Access API](https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API) is not currently implemented in Firefox. So that should be altered.

If I try to manually access the sourceScripts in the console, I can get a reader but they just exit immediately with done. So I don't see any actual script content.

**Comment by scriptjunkie** [comment]
Here's the scripts extracted from the "sources" view of the debugger [https://scriptjunkie.us/whatsapp.zip](https://scriptjunkie.us/whatsapp.zip)

**Comment by ezzak** [comment]
#240 should resolve this issue
