### ISSUE TITLE
It takes multiple retries for WhatsApp to be validated

### ISSUE THREAD

**Issue by lubo** [facebookincubator/meta-code-verify#254]
When accessing https://web.whatsapp.com/, I usually get:

>Possible Risk Detected
>
>Cannot validate the page due to another browser extension. Consider pausing the other extension(s) and re-trying.

even when no extensions are active. If I keep pressing Retry while WhatsApp is loading, it becomes validated after several retries. However, https://www.messenger.com/ works just fine all the time.

I've been Google Chrome and this is still an issue on version 117.0.5938.62.

**Comment by rich-hansen** [comment]
What happens if you uninstall the other extensions?

The reason I say so, is we only show that particular warning if there is a script inserted that isn't in the manifest, *but* we recognize as a deterministic script inserted by another extension.

So, if you're getting that message even when they're disabled, I think it means that somehow whichever extension is *still* inserting a script into the page.

I'd be curious if you can repro with no extensions installed.

Also, if you don't mind sharing, which extensions do you have installed, but disabled so we can try to repro?

Thanks!

**Comment by lubo** [comment]
I tried it in a fresh Chrome profile with no extensions and the behavior was the same. I even tried it in Chromium without any previous user data and nothing changed.

Normally, I have the following extensions installed:

- [Adblock Plus](https://chrome.google.com/webstore/detail/adblock-plus-free-ad-bloc/cfhdojbkjhnklbpkdaibdccddilifddb) (disabled all the time)
- [Code Verify](https://chrome.google.com/webstore/detail/code-verify/llohflklppcaghdpehpbklhlfebooeog)
- [D.Bridge 2](https://chrome.google.com/webstore/detail/dbridge-2/fngbdhimbgbonhlibfmiemipheabfdmj) (allowed for `https://schranka.slovensko.sk/*` only)
- [Google Docs Offline](https://chrome.google.com/webstore/detail/google-docs-offline/ghbmnnjooekpmoecnnnilnnbdlolhkhi)
- [Google Translate](https://chrome.google.com/webstore/detail/google-translate/aapbdbdomjkkjkaonfhkkikfgjllcleb)
- [uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm)

**Comment by scumjr** [comment]
Hello,

I encounter the same issue on Chromium (version `118.0.5993.70 (Official Build) snap (64-bit)`) with no extension installed but Code Verify (version `3.2.1`). Here's a Developer Tools screenshot:

![Screenshot from 2023-10-18](https://github.com/facebookincubator/meta-code-verify/assets/12125965/919e64dc-a1fc-47e9-b368-8f9cea27c336)

According to the following DEBUG message, the content of `https://web.whatsapp.com/libsignal-protocol-ee5b8ba.min.js` seems to be empty (it's confirmed by the SHA-256 hash):

```
processed the RAW_JS, response is e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 {"valid":false,"hash":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","reason":"Error: hash does not match WHATSAPP, 2.2344.53, unmatched JS is "}
```

**Comment by ezzak** [comment]
This issue should now be resolved please re-flag if you still see issues. @lubo @scumjr

**Comment by lubo** [comment]
Waiting for new release.

**Comment by lubo** [comment]
On v3.3, it still required a couple of page refreshes. However, v3.4 seems to work as expected.
