### ISSUE TITLE
Verification failure

### ISSUE THREAD

**Issue by dboreham** [facebookincubator/meta-code-verify#300]
I'm probably holding it wrong, but in the middle of a quest to understand the state of the art in browser code verification, I stumbled upon this Chrome extension. Installed to kick the tires. And...I get a red verification failure on both facebook.com and instagram.com. I'm running Chrome 120.0.6099.225 on Windows. I'm guessing that I'm _not_ being MITM'ed but curious if this thing is maintained still or other reasons why I'd see a validation failure. Thanks. PS I already checked the support page (disabled all other Chrome extensions) and checked the recommended X channel and blog, but nothing there about code verify being broken.

**Comment by ezzak** [comment]
Does this persist on refresh?

**Comment by dboreham** [comment]
> Does this persist on refresh?

Yes it does. Also same deal on another machine (after I became paranoid that perhaps I _was_ being MITM'ed).

**Comment by ezzak** [comment]
Can you try once more?

**Comment by ezzak** [comment]
Can you check if the issue is resolved now?

**Comment by dboreham** [comment]
Yes, I get the green light now, thanks.
