### ISSUE TITLE
Binary transparency archives no longer being published

### ISSUE THREAD

**Issue by brxxn** [facebookincubator/meta-code-verify#322]
It seems like newer revs cannot be downloaded through binary transparency archives, meaning that the "Download source code" button in the extension no longer works. This rev is around 24 hours old and still hasn't been published: https://www.facebook.com/btarchive/1012994568/facebook

Downloading source code is very helpful for security research so I would love to see this get fixed, thanks!

Edit: It seems to have now published, but it appears to be a little more behind than usual (usually gets published in less than 24 hours after rev is deployed). However, new revs get published often, so extension users likely aren't able to use the button if revs continue to be this delayed.

**Comment by ezzak** [comment]
Hi Brian, 

Some of the underlying publishing pipelines were backed up, causing a delay in the publishing process. They have now caught back up to speed.

Please feel free to reopen if you notice this again, thanks!
