### ISSUE TITLE
log in to facebook account

### ISSUE THREAD

**Issue by topp24** [facebookincubator/meta-code-verify#331]
I cannot log in to my facebook account because two-factor authentication is on and the hacker has all three options. so even if i have already changed my email and password, i cannot log in to my account. how to log in to my account without two-factor authentication options. And i have already submit my ID since my account was created based on our products name called 'Pladco Jerrycan'. It is not a person name.

**Comment by ezzak** [comment]
Please contact Facebook support https://www.facebook.com/help/1216349518398524

This is the wrong channel.
