### ISSUE TITLE
Longtail hash in application manifest

### ISSUE THREAD

**Issue by AadarshSree** [facebookincubator/meta-code-verify#333]
In the manifest, there are three hashes the 'Longtail' hash, the 'main' hash, and the 'combined' hash (roothash). 
I understand that the main hash is the SHA-256 hash of the array (of JS file hashes) present in the manifest and the combined hash is SHA256(Longtail+main).

In validateMetaCompanyManifest.ts the if condition on line 49 indicates that either the main or longtail hash can match the hash computed by the extension to be valid.

Can someone explain what is a longtail hash and how it is computed?

**Comment by AadarshSree** [comment]
Hi @ezzak would you be able to provide any insight into this?

**Comment by ezzak** [comment]
Not exactly, let's take a step back.

"Main" and "longtail" are names of "sub"  manifests that when hashed together should checksum to the root hash.

There is nothing special about the naming, you can call them "A" and "B"... we refer to the longtail this way as it usually included less frequently used resources on the page.

`validateMetaCompanyManifest` is called for each of these sub manfiests, ensures that they are either a longtail or main and that when checksumed with the other type of manifests they hash to the root.


I've attached a helpful visual below.

![image](https://github.com/user-attachments/assets/2b89a8a9-71fe-4e5f-87a5-f341dcd76431)
