### ISSUE TITLE
Reporting security issues?

### ISSUE THREAD

**Issue by jupenur** [facebookincubator/meta-code-verify#338]
Should security issues be reported privately through the Meta Bug Bounty program or publicly through GitHub issues? The security policy seems clear on the bug bounty program being the correct channel, but I have not been able to get a response to my reports submitted there weeks ago.

**Comment by ezzak** [comment]
The bug bounty program is indeed the correct channel.

**Comment by ezzak** [comment]
Sometimes there is a bit of delay due to our backlog of reports, please reopen if your issue is not addressed soon through the official channels and we might be able to investigate further.

**Comment by jupenur** [comment]
@ezzak I still have no response from the bug bounty program and I'm unable to reopen this ticket. What's the correct path forward here?
